backend:
  name: git-gateway

media_folder: source/images/uploads
public_folder: /images/uploads

#publish_mode: editorial_workflow #optional, enables publishing workflow

collections:
  - name: service
    label: Service
    format: yml
    extension: yml
    folder: data/services/
    create: true
    slug: '{{title}}'
    fields:
      - {label: Title, name: title, widget: string, required: true}
      - {label: Publish Date, name: date, widget: datetime}
      - {label: Image, name: image, widget: image, required: true}
      - {label: Body, name: body, widget: markdown}
      - {label: Link, name: link, widget: string}

  - name: blog
    label: Blog
    folder: source/posts/
    extension: .html.md
    format: frontmatter
    create: true
    slug: '{{title}}'
    fields:
      - {label: Title, name: title, widget: string, required: true}
      - {label: Publish Date, name: date, widget: datetime}
      - {label: Description, name: description, widget: string}
      - {label: Image, name: image, widget: image}
      - {label: Body, name: body, widget: markdown}

  - name: pages
    label: Pages
    files:
      - file: "data/pages/home.yml"
        label: Homepage
        name: home
        fields:
          - label: Hero
            name: hero
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Image, name: image, widget: image}
          - {label: Video, name: video, widget: string}

      - file: "data/pages/workshops.yml"
        label: Group Workshops
        name: workshops
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Slug, name: slug, widget: string}
          - {label: Image, name: image, widget: image, required: false}
          - {label: Body, name: body, widget: markdown}
          - {label: Sidebar, name: sidebar, widget: markdown, required: false}

      - file: "data/pages/one-to-one.yml"
        label: One to One
        name: one-to-one
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Slug, name: slug, widget: string}
          - {label: Image, name: image, widget: image, required: false}
          - {label: Body, name: body, widget: markdown}
          - {label: Sidebar, name: sidebar, widget: markdown, required: false}

      - file: "data/pages/six-to-seven.yml"
        label: Year 6 to 7
        name: six-to-seven
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Slug, name: slug, widget: string}
          - {label: Image, name: image, widget: image, required: false}
          - {label: Body, name: body, widget: markdown}
          - {label: Sidebar, name: sidebar, widget: markdown, required: false}

      - file: "data/pages/about.yml"
        label: About Me
        name: about
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Slug, name: slug, widget: string}
          - {label: Image, name: image, widget: image, required: false}
          - {label: Body, name: body, widget: markdown}
          - {label: Sidebar, name: sidebar, widget: markdown, required: false}

      - file: "data/pages/contact.yml"
        label: Contact
        name: contact
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Slug, name: slug, widget: string}
          - {label: Image, name: image, widget: image, required: false}
          - {label: Body, name: body, widget: markdown}
          - {label: Sidebar, name: sidebar, widget: markdown, required: false}

  - name: settings
    label: Settings
    files:
      - file: data/settings/navigation.yml
        label: Navigation
        name: navigation
        fields:
          - label: Navigation
            name: nav_items
            widget: list
            fields:
              - {label: Label, name: label, widget: string}
              - {label: Path, name: path, widget: string}
      - file: data/settings/general.yml
        label: General
        name: general
        fields:
          - {label: Face, name: face, widget: image}
